import type { AnalysisLayer, VisualStyle } from '../types/data';
export type { AnalysisLayer, VisualStyle } from '../types/data';
export const LAYER_CONFIG: Record<AnalysisLayer, {label: string; defaultMetric: string; defaultStyle: VisualStyle; metrics: string[]; styles: VisualStyle[]}> = {
  building: {label:'Building Capacity', defaultMetric:'hgl_family_opportunity_score', defaultStyle:'3d', metrics:['hgl_family_opportunity_score','hgl_building_opportunity_score','under5_capacity_signal','family_residential_capacity_units','residential_units_raw','residential_units','residential_capacity_units','estimated_household_capacity','preschool_age_capacity_signal','family_anchor_count_250m','under5_family_context_score','parent_caregiver_context_score','nearest_family_anchor_distance','nearby_preschool_count_250m','nearby_competitor_count_250m','preschool_access_signal','competitor_pressure_signal','residential_use_type','income_signal'], styles:['3d','heatmap','flat','mixed']},
  street: {label:'Street Capacity Signal', defaultMetric:'hgl_street_opportunity_score', defaultStyle:'flat', metrics:['hgl_street_opportunity_score','street_under5_capacity_signal','street_preschool_age_demand_signal','residential_capacity_nearby','income_signal','family_anchor_density','school_preschool_anchor_density','competitor_density','ooh_asset_density','transit_access_signal'], styles:['flat','3d']},
  blockGroup: {label:'Official Block Group Aggregate', defaultMetric:'under5_official_bg', defaultStyle:'3d', metrics:['under5_official_bg','official_under5_share','official_population','official_households','median_household_income','households_with_children_pct','family_households_pct','chinese_spoken_home_pct','spanish_spoken_home_pct','hgl_opportunity_score'], styles:['3d','heatmap','flat']},
  censusBlock: {label:'Census Block Context', defaultMetric:'hgl_opportunity_score', defaultStyle:'3d', metrics:['hgl_opportunity_score'], styles:['3d','heatmap','flat']},
  zip: {label:'ZIP Overview', defaultMetric:'under5', defaultStyle:'3d', metrics:['population','under5','under5_pct','median_household_income','households_with_children_pct','family_households_pct','chinese_spoken_home_pct','spanish_spoken_home_pct','hgl_opportunity_score'], styles:['3d','heatmap','flat']},
  ooh: {label:'OOH Inventory', defaultMetric:'hgl_relevance_score', defaultStyle:'inventory', metrics:['hgl_relevance_score','family_anchor_count_250m','family_context_relevance_score','availability_confidence','family_anchor_proximity','school_preschool_proximity','transit_proximity'], styles:['inventory','heatmap']},
  combined: {label:'Combined Opportunity', defaultMetric:'hgl_opportunity_score', defaultStyle:'mixed', metrics:['hgl_opportunity_score'], styles:['mixed','heatmap','flat']}
};
export const METRIC_LABELS: Record<string,string> = {
 population:'Population', official_population:'Official Population', official_households:'Official Households', under5:'Official Under 5 Count', under5_official_bg:'Official Under 5 Count', under5_official_tract:'Official Tract Under 5 Count', under5_pct:'Official Under 5 Share', official_under5_share:'Official Under 5 Share', under5_share:'Official Under 5 Share', estimated_under5_signal:'Modeled Under-5 Capacity Signal', under5_capacity_signal:'Under-5 Capacity Signal', modeled_under5_capacity_signal:'Modeled Under-5 Capacity Signal', street_under5_capacity_signal:'Under-5 Capacity Signal', street_preschool_age_demand_signal:'Preschool-Age Demand Signal', preschool_age_capacity_signal:'Preschool-Age Capacity Signal', residential_capacity_nearby:'Nearby Residential Capacity Signal', units_res:'Residential Units', residential_units:'Residential Units', residential_capacity_units:'Residential Capacity Units', estimated_household_capacity:'Estimated Household Capacity', residential_use_type:'Building Use Type', income_signal:'Income Signal', median_household_income:'Median Household Income', households_with_children_pct:'Households With Children %', family_households_pct:'Family Households %', chinese_spoken_home_pct:'Chinese Spoken at Home %', spanish_spoken_home_pct:'Spanish Spoken at Home %', hgl_opportunity_score:'HGL Opportunity Score', hgl_building_opportunity_score:'HGL Building Opportunity Score', hgl_family_opportunity_score:'HGL Family Opportunity Score', family_residential_capacity_units:'Family Residential Capacity Units', residential_units_raw:'Raw Residential Units', hgl_street_opportunity_score:'HGL Street Opportunity Score', family_anchor_density:'Family Anchor Density', school_preschool_anchor_density:'School / Preschool Density', competitor_density:'Competitor Density', ooh_asset_density:'OOH Asset Density', transit_access_signal:'Transit Access Signal', hgl_relevance_score:'OOH Relevance Score'
};
