import { formatValue } from '../utils/format';
import { useMemo, useState } from 'react';
export default function DataTable({features}: {features:any[]}){
 const [sortKey,setSortKey]=useState('hgl_opportunity_score');
 const rows=useMemo(()=>[...(features||[])].slice(0,250).sort((a,b)=>Number(b.properties?.[sortKey]||0)-Number(a.properties?.[sortKey]||0)),[features,sortKey]);
 if(!rows.length) return null;
 const sample = rows[0]?.properties || {};
 const cols = sample.street_segment_id ? [['street_name','Street'],['under5_capacity_signal','Under-5 Capacity Signal'],['income_signal','Income Signal'],['family_anchor_density','Family Anchors'],['ooh_asset_density','OOH Density'],['hgl_street_opportunity_score','Street Score'],['data_tier','Tier']] : sample.address_or_label ? [['address_or_label','Building'],['zipcode','ZIP'],['residential_use_type','Use'],['residential_capacity_units','Capacity Units'],['estimated_household_capacity','HH Capacity'],['under5_capacity_signal','Under-5 Capacity Signal'],['hgl_building_opportunity_score','HGL Score'],['capacity_model_confidence','Confidence']] : sample.under5_official_bg !== undefined ? [['display_label','Block Group'],['under5_official_bg','Official Under 5 Count'],['official_under5_share','Official Under 5 Share'],['official_population','Official Population'],['official_households','Official Households'],['data_tier','Tier']] : [['zipcode','ZIP'],['under5','Official Under 5'],['median_household_income','Income'],['hgl_opportunity_score','Score']];
 return <div className="tableWrap"><table><thead><tr>{cols.map(([k,l])=><th key={k} onClick={()=>setSortKey(k)}>{l}</th>)}</tr></thead><tbody>{rows.map((f:any,i:number)=><tr key={f.properties?.street_segment_id||f.properties?.bbl||f.properties?.geoid||f.properties?.zipcode||i}>{cols.map(([k])=><td key={k}>{formatValue(f.properties?.[k], k.includes('income')?'currency':k.includes('pct')||k.includes('share')?'percent':k.includes('score')||k.includes('signal')?'score':undefined)}</td>)}</tr>)}</tbody></table></div>
}
